---
title: "Project"
author: "Kangxin Bao - kb2900"
date: "April 8, 2017"
output: html_document
---

## The Distribution of Collisions

```{r}
library(readr)
library(ggplot2)
library(ggmap)
#collisions since 06/2016 and evolved bicycles
collisions <- read_csv("C:/Users/Cynthia/Documents/#Courseworks#/2017 Spring/Data Visualization/Final Project/NYPD_Motor_Vehicle_Collisions.csv")
collisions <- subset(collisions, `VEHICLE TYPE CODE 1`=="BICYCLE" | `VEHICLE TYPE CODE 2`=="BICYCLE")
collisions$year <- substring(as.character(collisions$DATE),7,10)
collisions$month <- substring(as.character(collisions$DATE),1,2)
collisions$paste <- paste0(collisions$year, collisions$month)
collisions <- subset(collisions, paste > 201306 & paste < 201701)

manhattan <- get_map("Manhattan", zoom=12, source="stamen",maptype="toner-background")
g <- ggmap(manhattan, base_layer=ggplot(collisions, aes(x=LONGITUDE,y=LATITUDE))) 
g1 <- g + geom_point(size=0.4, alpha=0.4, color="red") 
g1

g2 <- g + geom_density_2d(aes(x=LONGITUDE, y=LATITUDE), data=collisions, size=1, color="blue", alpha=0.3) + theme(legend.position = "none")
g2

library(cowplot)
plot_grid(g1, g2, ncol = 2, nrow = 1)
```

## Changes in the Distribution of Collisions over Years

```{r}
library(ggthemes)
g3 <- g + geom_density2d(aes(x=LONGITUDE, y=LATITUDE), data=collisions, color="lightblue", size=0.6, bins=12) + 
  stat_density2d(aes(x=LONGITUDE, y=LATITUDE, fill=..level..,alpha = ..level.., group=year), data=collisions, geom="polygon") +
  scale_alpha(range = c(0.00, 0.5), guide=FALSE) +
  scale_fill_gradient(low = "yellow", high = "red") +
  theme_map() + theme(legend.position = "right") +
  theme(strip.text.x = element_text(size = 14, face=2)) +
  facet_wrap(~year, ncol = 2) 
g3
```

## Overall Distribution of each Neighbourhood

```{r}
library(rgdal)
library(tmap)
nybb <- readOGR("c:/Users/Cynthia/Documents/#courseworks#/2017 Spring/Data Visualization/Assignment/Assignment 2/neighbourhoods.geojson", "OGRGeoJSON")

collision_loc <- as.data.frame(table(collisions$`ZIP CODE`))
colnames(collision_loc) <- c("zipcode", "freq")

library(dplyr)
combined <- nycc@data %>% left_join(collision_loc, by = c(ZCTA5CE10 = "zipcode"))
combined$freq.x <- NULL
combined[is.na(combined)] <- 0
nycc@data <- combined
library(leaflet)

collision_loc_y <- as.data.frame(table(collisions$`ZIP CODE`, collisions$year))

## overall neighbourhood-different map
collisions$injured_killed <- collisions$`NUMBER OF PERSONS INJURED` + collisions$`NUMBER OF PERSONS KILLED`
names(collisions)[names(collisions) == "ZIP CODE"] <- "ZIPCODE"
attributes <- subset(collisions, select = c("ZIPCODE", "LONGITUDE", "LATITUDE", "year", "month", "injured_killed"))
attributes <- na.omit(attributes)
points <- attributes[, c("LONGITUDE", "LATITUDE")]

spoints <- SpatialPointsDataFrame(points, attributes)

#coordinates(points) =~ LATITUDE + LONGITUDE 
proj4string(spoints) <- CRS("+proj=longlat")
spoints = spTransform(spoints, CRS("+proj=longlat +datum=WGS84"))
nybb = spTransform(nybb, CRS("+proj=longlat +datum=WGS84"))

lpoints <- over(spoints, nybb)
lpoints3 <- over(spoints, nycb)
nyc.name <- cbind(attributes, lpoints)
nyc.name3 <- cbind(attributes, lpoints3)
nyc.name3 <- na.omit(nyc.name3)
points <- nyc.name3[, c("LONGITUDE", "LATITUDE")]
nyc.name$ZIPCODE <- as.character(nyc.name$ZIPCODE)

attributes2 <- nyc.name3[,c("ZIPCODE","LONGITUDE","LATITUDE","year","month","injured_killed","NTAName")]
attributes2 <- na.omit(attributes2)
spoints <- SpatialPointsDataFrame(points, attributes2)

n1 <- as.data.frame(table(nyc.name$neighbourhood))
colnames(n1) <- c("neighbourhood", "Frequency")
n2 <- as.data.frame(aggregate(injured_killed ~ neighbourhood, data = nyc.name, sum))
n3 <- merge(n1, n2, by="neighbourhood")

combined2 <- nybb@data %>% left_join(n3, by = c(neighbourhood = "neighbourhood"))
nybb@data <- combined2
nybb <- subset(nybb, nybb@data$neighbourhood_group != "Staten Island")

t1 <- tm_shape(nybb) + tm_fill("Frequency", title=c("Collisions")) + tm_text("neighbourhood", size=.6, shadow=TRUE, bg.color="white", bg.alpha=.25, remove.overlap=TRUE) #+ layout
t2 <- tm_shape(nybb) + tm_fill("injured_killed", palette="Blues", title=c("Injured/killed Persons")) + tm_text("neighbourhood", size=.6, shadow=TRUE, bg.color="white", bg.alpha=.25, remove.overlap=TRUE) #+ layout
tmap_arrange(t1, t2, asp = 1)

```

## Interactive Map

```{r}
##change over year

##new data
nycb <- readOGR("C:/Users/Cynthia/Documents/#Courseworks#/2017 Spring/Data Visualization/Final Project/nynta_17a/nynta_17a/.","nynta")
nycb = spTransform(nycb, CRS("+proj=longlat +datum=WGS84"))
#nycb <- subset(nycb, nycb@data$neighbourhood_group != "Staten Island")
lpoints2 <- over(spoints, nycb)
nyc.name2 <- cbind(attributes, lpoints2)

##no year
n11 <- as.data.frame(table(nyc.name2$NTAName))
colnames(n11) <- c("neighbourhood", "Frequency")
n22 <- as.data.frame(aggregate(injured_killed ~ NTAName, data = nyc.name2, sum))
colnames(n22)[1] <- c("neighbourhood")
n33 <- merge(n11, n22, by="neighbourhood")

##with year
nyear11 <- as.data.frame(table(nyc.name2$NTAName, nyc.name2$year))
colnames(nyear11) <- c("neighbourhood", "year", "Frequency")
nyear22 <- as.data.frame(aggregate(injured_killed ~ NTAName + year, data = nyc.name2, sum))
colnames(nyear22)[1] <- c("neighbourhood")
nyear33 <- merge(nyear11, nyear22, by = c("neighbourhood","year"))
nyear33.1 <- subset(nyear33, nyear33$year == "2013")
nyear33.2 <- subset(nyear33, nyear33$year == "2014")
nyear33.3 <- subset(nyear33, nyear33$year == "2015")
nyear33.4 <- subset(nyear33, nyear33$year == "2016")

nycb.year1 <- nycb
combined3 <- nycb.year1@data %>% left_join(nyear33.1, by = c(NTAName= "neighbourhood"))
nycb.year1@data <- combined3

nycb.year2 <- nycb
nycb.year2@data <- left_join(nycb.year2@data, nyear33.2, by = c(NTAName= "neighbourhood"))

nycb.year3 <- nycb
nycb.year3@data <- left_join(nycb.year3@data, nyear33.3, by = c(NTAName= "neighbourhood"))

nycb.year4 <- nycb
nycb.year4@data <- left_join(nycb.year4@data, nyear33.4, by = c(NTAName= "neighbourhood"))

```

### Interactive map about injured/killed

```{r}
spoints1 <- subset(spoints, spoints@data$year == "2013")
spoints2 <- subset(spoints, spoints@data$year == "2014")
spoints3 <- subset(spoints, spoints@data$year == "2015")
spoints4 <- subset(spoints, spoints@data$year == "2016")

in2 = leaflet(nycb) %>% 
  addTiles("http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png") %>% 
  setView(lat=40.7, lng=-73.9 , zoom=11) %>%
  addPolygons(data = nycb, fill = F, weight = 1, color = "#3399FF") %>%
  addCircleMarkers(group = "2013", 
                   data=spoints1, weight=1, radius=~spoints1$injured_killed*2.5, 
                   opacity=spoints1$injured_killed/5, 
                   fillOpacity=spoints1$injured_killed/5, 
                   color=~colorNumeric(palette = "RdYlGn", domain = spoints1$injured_killed)(spoints1$injured_killed), 
                   popup=~paste("Neighborhood: ",spoints1$NTAName,"<br/>",
                                "Persons Injured/killed: ",spoints1$injured_killed)) %>%
  addCircleMarkers(group = "2014", 
                   data=spoints1, weight=1, radius=~spoints2$injured_killed*2.5, 
                   opacity=spoints2$injured_killed/5, 
                   fillOpacity=spoints2$injured_killed/5, 
                   color=~colorNumeric(palette = "RdYlGn", domain = spoints2$injured_killed)(spoints2$injured_killed), 
                   popup=~paste("Neighborhood: ", spoints2$NTAName,"<br/>",
                                 "Persons Injured/killed:",spoints2$injured_killed)) %>%
  addCircleMarkers(group = "2015", 
                   data=spoints1, weight=1, radius=~spoints3$injured_killed*2.5,
                   opacity=spoints3$injured_killed/5, 
                   fillOpacity=spoints3$injured_killed/5, 
                   color=~colorNumeric(palette = "RdYlGn", domain = spoints2$injured_killed)(spoints3$injured_killed), 
                   popup=~paste("Neighborhood: ",spoints3$NTAName,"<br/>",
                                 "Persons Injured/killed:",spoints3$injured_killed)) %>%
  addCircleMarkers(group = "2016", 
                   data=spoints1, weight=1, radius=~spoints4$injured_killed*2.5, 
                   opacity=spoints4$injured_killed/5, 
                   fillOpacity=spoints4$injured_killed/5, 
                   color=~colorNumeric(palette = "RdYlGn", domain = spoints2$injured_killed)(spoints4$injured_killed), 
                   popup=~paste("Neighborhood: ",spoints4$NTAName,"<br/>",
                                 "Persons Injured/killed:",spoints4$injured_killed)) %>%
  addLayersControl(
    #baseGroups = c("OpenStreetMap"),
    overlayGroups = c("2013","2014","2015","2016"),
    options = layersControlOptions(collapsed = TRUE))
in2 %>% hideGroup(c("2014","2015","2016"))

in2_draft = leaflet(nycb) %>% 
  addTiles() %>% 
  setView(lat=40.7, lng=-73.9 , zoom=11) %>%
  addPolygons(data = nycb, fill = F, weight = 1, color = "#3399FF") %>%
  addCircleMarkers(group = "2013", 
                   data=spoints1, weight=1, radius=~spoints1$injured_killed*2.5,
                   fillOpacity=spoints1$injured_killed/5, 
                   color=~colorNumeric(palette = "Reds", domain = spoints1$injured_killed)(spoints1$injured_killed), 
                   popup=~paste("Neighborhood: ",spoints1$NTAName,"<br/>",
                                "Persons Injured/killed: ",spoints1$injured_killed)) %>%
  addCircleMarkers(group = "2014", 
                   data=spoints1, weight=1, radius=~spoints2$injured_killed*2.5, 
                   fillOpacity=spoints2$injured_killed/5, 
                   color=~colorNumeric(palette = "Oranges", domain = spoints2$injured_killed)(spoints2$injured_killed), 
                   popup=~paste("Neighborhood: ", spoints2$NTAName,"<br/>",
                                 "Persons Injured/killed:",spoints2$injured_killed)) %>%
  addCircleMarkers(group = "2015", 
                   data=spoints1, weight=1, radius=~spoints3$injured_killed*2.5,
                   fillOpacity=spoints3$injured_killed/5, 
                   color=~colorNumeric(palette = "Greens", domain = spoints2$injured_killed)(spoints3$injured_killed), 
                   popup=~paste("Neighborhood: ",spoints3$NTAName,"<br/>",
                                 "Persons Injured/killed:",spoints3$injured_killed)) %>%
  addCircleMarkers(group = "2016", 
                   data=spoints1, weight=1, radius=~spoints4$injured_killed*2.5, 
                   fillOpacity=spoints4$injured_killed/5, 
                   color=~colorNumeric(palette = "Purples", domain = spoints2$injured_killed)(spoints4$injured_killed), 
                   popup=~paste("Neighborhood: ",spoints4$NTAName,"<br/>",
                                 "Persons Injured/killed:",spoints4$injured_killed)) %>%
  addLayersControl(
    #baseGroups = c("OpenStreetMap"),
    overlayGroups = c("2013","2014","2015","2016"),
    options = layersControlOptions(collapsed = TRUE))
in2_draft %>% hideGroup(c("2014","2015","2016"))

```

## ShinyApp

```{r}
nyc.shiny <- nyc.name2[, c("NTAName", "year", "month", "injured_killed")]
nyc.shiny$month <- paste(nyc.shiny$year, nyc.shiny$month, sep = "-")
shiny1 <- as.data.frame(table(nyc.shiny$NTAName, nyc.shiny$month))
colnames(shiny1) <- c("NTAName", "month", "Frequency")
shiny2 <- as.data.frame(aggregate(injured_killed ~ NTAName + month, data = nyc.shiny, sum))
shiny3 <- merge(shiny1, shiny2, by=c("NTAName", "month"))
shiny3$month <- as.POSIXct(paste(as.character(shiny3$month),"-01",sep=""),tz = "EST")

library(shiny)
library(plotly)
ui <- fluidPage(
  fluidRow(column(width=5,offset = 1,leafletOutput("map",width = "100%",height = 700)),
           column(width=5,offset = 0,fluidRow(plotlyOutput(outputId = "firstplot",width = "100%",height = 350)),fluidRow(plotlyOutput(outputId = "secondplot",width = "100%",height = 350)))
))

nycb.year1@data$id <- seq(1,nrow(nycb.year1@data),by=1)
nycb.year2@data$id <- seq(1,nrow(nycb.year1@data),by=1)
nycb.year3@data$id <- seq(1,nrow(nycb.year1@data),by=1)
nycb.year4@data$id <- seq(1,nrow(nycb.year1@data),by=1)
centers = coordinates(nycb)
server <- function(input, output,session){
  output$map <- renderLeaflet({
    leaflet(nycb) %>% 
      addTiles("http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png") %>%
      setView(lat=40.736512, lng=-73.972151 , zoom=12) %>%
      addPolygons(group = "2013",
                  data=nycb.year1,
                  stroke = T,color=~colorNumeric(palette = "magma", domain = nycb.year1$Frequency)(nycb.year1$Frequency), 
                  fillOpacity = 0.5, smoothFactor = 0.5, weight = 1,opacity =1, 
                  fillColor = ~colorNumeric(palette = "magma", domain = nycb.year1$Frequency)(nycb.year1$Frequency),
                  highlightOptions = highlightOptions(weight = 3),
                  label = paste("Neighborhood: ",nycb.year1$NTAName,"\n", "Year: ",nycb.year1$year,"\n", "Bicycle Collision: ",nycb.year1$Frequency),
                  layerId = nycb.year1@data$id) %>%
      addPolygons(group = "2014",
                  data=nycb.year2,
                  stroke = T, fillOpacity = 0.5, smoothFactor = 0.5,
                  weight = 1, opacity=1, color=~colorNumeric(palette = "magma", domain = nycb.year2$Frequency)(nycb.year2$Frequency), 
                  fillColor = ~colorNumeric(palette = "magma", domain = nycb.year2$Frequency)(nycb.year2$Frequency), 
                  highlightOptions = highlightOptions(weight = 3),
                  label = paste("Neighborhood: ",nycb.year2$NTAName,"\n", "Year: ",nycb.year2$year,"\n", "Bicycle Collision: ",nycb.year2$Frequency),layerId = nycb.year2@data$id) %>%
      addPolygons(group = "2015",
                  data=nycb.year3,
                  stroke = FALSE, fillOpacity = 0.5, smoothFactor = 0.5, 
                  color = ~colorNumeric(palette = "magma", domain = nycb.year3$Frequency)(nycb.year3$Frequency),
                  opacity = 1,weight = 1,
                  fill = ~colorNumeric(palette = "magma", domain = nycb.year3$Frequency)(nycb.year3$Frequency),
                  highlightOptions = highlightOptions(weight = 1),
                  popup = paste("Neighborhood: ",nycb.year3$NTAName,"\n", "Year: ",nycb.year3$year,"\n", "Bicycle Collision: ",nycb.year3$Frequency),layerId = nycb.year3@data$id) %>%
      addPolygons(group = "2016",
                  data=nycb.year4,
                  stroke = FALSE, fillOpacity = 0.5, smoothFactor = 0.5, weight =1, opacity =1,
                  fillColor = ~colorNumeric(palette = "magma", domain = nycb.year4$Frequency)(nycb.year4$Frequency),
                  color = ~colorNumeric(palette = "magma", domain = nycb.year4$Frequency)(nycb.year4$Frequency),
                  highlightOptions = highlightOptions(weight =1 ),
                  popup = paste("Neighborhood: ",nycb.year4$NTAName,"\n", "Year: ",nycb.year4$year,"\n", "Bicycle Collision: ",nycb.year4$Frequency),layerId = nycb.year4@data$id) %>%
      addLayersControl(
    #baseGroups = c("OpenStreetMap"),
        baseGroups = c("2013","2014","2015","2016"),
        options = layersControlOptions(collapsed = TRUE)) %>% hideGroup(c("2014","2015","2016"))

    })
  
  observeEvent(input$map_shape_click, {
    click <- input$map_shape_click
    name <- as.character(nycb@data$NTAName)[click$id]
    output$firstplot <- renderPlotly({plot_ly(data = filter(shiny3,NTAName==name),x=~month,y=~Frequency, type = "scatter",mode = "lines") %>% layout(title = "Traffic Collisions Involving Bicyclists",scene=list(xaxis = list(title ="Month"),yaxis=list(title = "Frequency")))})
    output$secondplot <- renderPlotly({plot_ly(data = filter(shiny3,NTAName==name),x = ~month,y=~injured_killed,type = "scatter",mode = "lines") %>% layout(title = "Traffic Collisions Involving Bicyclists",scene=list(xaxis = list(title ="Month"),yaxis=list(title = "Injured/Killed")))})
      })
        
}
shinyApp(ui = ui, server = server)
```
